import type { WorldSnapshot } from '../../../src/core/types.js';

export class CommandCenter {
 readonly root=document.createElement('div');private status=document.createElement('div');private timeline=document.createElement('div');private stats=document.createElement('div');private actions=document.createElement('div');
 constructor(actions:{rupture:()=>void,isolate:()=>void,suppress:()=>void,reset:()=>void,overview:()=>void,incident:()=>void}){
  const style=document.createElement('style');style.textContent=`*{box-sizing:border-box}html,body,#app{margin:0;width:100%;height:100%;overflow:hidden;background:#071018;font-family:Inter,ui-sans-serif,system-ui;color:#e9f4f8}button{font:inherit}.hl-glass{background:linear-gradient(145deg,rgba(8,19,27,.9),rgba(8,19,27,.68));border:1px solid rgba(136,184,204,.18);box-shadow:0 16px 50px rgba(0,0,0,.28);backdrop-filter:blur(18px)}.hl-btn{border:1px solid #365160;background:#10232d;color:#dff5ff;padding:9px 12px;border-radius:9px;cursor:pointer;letter-spacing:.03em}.hl-btn:hover{background:#183542}.hl-danger{border-color:#8c3f34;background:#3b1916}.hl-accent{color:#65d6e8}.hl-muted{color:#78909c}.hl-kpi{font-size:24px;font-weight:650}.hl-event{padding:7px 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:11px}.hl-pill{display:inline-block;padding:3px 7px;border-radius:99px;background:#15313c;color:#75d8e5;font-size:10px;letter-spacing:.08em}`;document.head.appendChild(style);
  this.root.innerHTML=`<div class="hl-glass" style="position:fixed;left:18px;top:18px;width:330px;border-radius:14px;overflow:hidden;z-index:10"><div style="padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.08)"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:18px;font-weight:700;letter-spacing:.14em">HAZARDLENS</div><div class="hl-muted" style="font-size:10px;letter-spacing:.16em;margin-top:4px">INDUSTRIAL TWIN COMMAND</div></div><span class="hl-pill">LIVE</span></div></div></div>`;
  document.body.appendChild(this.root);const card=this.root.firstElementChild as HTMLElement;this.status.style.cssText='padding:14px 18px;border-bottom:1px solid rgba(255,255,255,.07)';this.stats.style.cssText='display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:14px 18px';this.actions.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:0 18px 16px';card.append(this.status,this.stats,this.actions);
  const add=(label:string,fn:()=>void,cls='')=>{const b=document.createElement('button');b.className=`hl-btn ${cls}`;b.textContent=label;b.onclick=fn;this.actions.appendChild(b)};add('RUPTURE P-017',actions.rupture,'hl-danger');add('ISOLATE LINE',actions.isolate);add('SUPPRESS FIRE',actions.suppress);add('RESET WORLD',actions.reset);add('OVERVIEW',actions.overview);add('INCIDENT CAM',actions.incident);
  this.timeline.className='hl-glass';this.timeline.style.cssText='position:fixed;right:18px;bottom:18px;width:330px;max-height:240px;overflow:hidden;border-radius:14px;padding:14px 16px;z-index:9';document.body.appendChild(this.timeline);
 }
 update(s:WorldSnapshot){const fires=s.twins.filter(t=>t.kind==='fire'&&t.active).length,releases=s.twins.filter(t=>t.kind==='release'&&t.active).length,critical=s.twins.filter(t=>t.integrity<.5&&['tank','pipe','wall'].includes(t.kind)).length;this.status.innerHTML=`<div style="display:flex;justify-content:space-between"><span class="hl-muted">FACILITY STATUS</span><b class="${fires?'':'hl-accent'}">${fires?'INCIDENT ACTIVE':'NOMINAL'}</b></div><div style="margin-top:7px;font-size:12px">Simulation T+ ${s.time.toFixed(1)} s · ${s.twins.length} live digital twins</div>`;this.stats.innerHTML=`<div><div class="hl-kpi">${fires}</div><div class="hl-muted" style="font-size:10px">FIRES</div></div><div><div class="hl-kpi">${releases}</div><div class="hl-muted" style="font-size:10px">PLUMES</div></div><div><div class="hl-kpi">${critical}</div><div class="hl-muted" style="font-size:10px">CRITICAL</div></div>`;const events=s.events.slice(-8).reverse();this.timeline.innerHTML=`<div style="display:flex;justify-content:space-between;margin-bottom:8px"><b>CAUSAL TIMELINE</b><span class="hl-muted">${s.events.length} EVENTS</span></div>${events.map(e=>`<div class="hl-event"><span class="hl-muted">${e.time.toFixed(1)}s</span> &nbsp; <b>${e.type}</b><br/><span class="hl-muted">${e.sourceId}${e.targetId?` → ${e.targetId}`:''}</span></div>`).join('')||'<div class="hl-muted" style="font-size:12px">Inject a fault to begin the causal replay.</div>'}`}
}
